
let productsDB = [
  {
    id: 1,
    title: "Jewellery",
    price: "1",
    imageUrl: "img/jewellery-2.jpg",
    imageUrl2: "img/jewellery-1.jpg",
    imageUrl3: "img/jewellery-3.jpg",
    imageUrl4: "img/jewellery-4.jpg",
    imageUrl5: "img/jewellery-5.jpg",
    des: "100000",
    qty: 1,
    ca: "Arrivals",
    category : "Product"
  },
    {
      id: 2,
      title: "Jewellery",
      price: 40,
      imageUrl: "img/jewellery-1.jpg",
      imageUrl2: "img/jewellery-2.jpg",
      imageUrl3: "img/jewellery-3.jpg",
      imageUrl4: "img/jewellery-5.jpg",
      imageUrl5: "img/jewellery-5.jpg",
      des: "100000",
      qty: 1,
      ca: "Trending",
      category : "Product"
    },
    {
      id: 3,
      title: "Jewellery",
      price: "200",
      imageUrl: "img/jewellery-5.jpg",
      imageUrl2: "img/jewellery-1.jpg",
      imageUrl3: "img/jewellery-3.jpg",
      imageUrl4: "img/jewellery-1.jpg",
      imageUrl5: "img/jewellery-2.jpg",
      des: "100000",
      qty: 1,
      ca: "Toprated",
      category : "Product"
    },
    {
      id: 4,
      title: "Jewellery",
      price: 400,
      imageUrl: "img/jewellery-1.jpg",
      imageUrl2: "img/jewellery-1.jpg",
      imageUrl3: "img/jewellery-3.jpg",
      imageUrl4: "img/jewellery-2.jpg",
      imageUrl5: "img/jewellery-5.jpg",
      des: "100",
      qty: 1,
      ca: "Arrivals",
      category : "Product"
    },
    {
      id: 5,
      title: "Jewellery",
      price: 40,
      imageUrl: "img/jewellery-3.jpg",
      imageUrl2: "img/jewellery-1.jpg",
      imageUrl3: "img/jewellery-2.jpg",
      imageUrl4: "img/jewellery-3.jpg",
      imageUrl5: "img/jewellery-5.jpg",
      des: "100000",
      qty: 1,
      ca: "Trending",
      category : "Product"
    },
    {
      id: 6,
      title: "Clothes",
      price: 40,
      imageUrl: "img/clothes-2.jpg",
      imageUrl2: "img/2.jpg",
      imageUrl3: "img/3.jpg",
      imageUrl4: "img/clothes-5.jpg",
      imageUrl5: "img/10.jpg",
      des: "100000",
      qty: 1,
      ca: "Toprated",
      category : "Product"
    },
    {
      id: 7,
      title: "Jacket",
      price: 40,
      imageUrl: "img/jacket-4.jpg",
      imageUrl2: "img/jacket-2.jpg",
      imageUrl3: "img/jacket-3.jpg",
      imageUrl4: "img/jacket-4.jpg",
      imageUrl5: "img/jacket-6.jpg",
      des: "100000",
      qty: 1,
      ca: "Toprated",
      category : "Product"
    },
    {
      id: 8,
      title: "Shorts",
      price: 40,
      imageUrl: "img/shorts-1.jpg",
      imageUrl2: "img/shorts-2.jpg",
      imageUrl3: "img/shorts3.jpg",
      imageUrl4: "img/shorts4.jpg",
      imageUrl5: "img/shorts5.jpg",
      des: "100000",
      qty: 1,
      ca: "Trending",
      category : "Product"
    },
    {
      id: 9,
      title: "Shirt",
      price: 40,
      imageUrl: "img/3.jpg",
      imageUrl2: "img/Shirt-3.jpg",
      imageUrl3: "img/Shirt-5.jpg",
      imageUrl4: "img/Shirt-4.jpg",
      imageUrl5: "img/Shirt-2.jpg",
      des: "100000",
      qty: 1,
      ca: "Trending",
      category : "Product"
    },
    {
      id: 10,
      title: "Clothes",
      price: 40,
      imageUrl: "img/clothes-2.jpg",
      imageUrl2: "img/2.jpg",
      imageUrl3: "img/3.jpg",
      imageUrl4: "img/clothes-5.jpg",
      imageUrl5: "img/10.jpg",
      des: "100000",
      qty: 1,
      ca: "Trending",
      category : "Product"
    },
    {
      id: 10,
      title: "Clothes",
      price: 40,
      imageUrl: "img/10.jpg",
      imageUrl2: "img/2.jpg",
      imageUrl3: "img/3.jpg",
      imageUrl4: "img/clothes-5.jpg",
      imageUrl5: "img/clothes-2.jpg",
      des: "100000",
      qty: 1,
      ca: "Trending",
      category : "Product"
    },
    {
      id: 11,
      title: "Clothes",
      price: 40,
      imageUrl: "img/jygfhj.jpg",
      imageUrl2: "img/2.jpg",
      imageUrl3: "img/3.jpg",
      imageUrl4: "img/clothes-5.jpg",
      imageUrl5: "img/clothes-2.jpg",
      des: "100000",
      qty: 1,
      ca: "Toprated",
      category : "Product"
    },
    {
      id: 12,
      title: "Jacket",
      price: 40,
      imageUrl: "img/jacket-5.jpg",
      imageUrl2: "img/jacket-2.jpg",
      imageUrl3: "img/jacket-3.jpg",
      imageUrl4: "img/jacket-4.jpg",
      imageUrl5: "img/jacket-6.jpg",
      des: "100000",
      qty: 1,
      ca: "Toprated",
      category : "Product"
    },
    {
      id: 13,
      title: "Shoes",
      price: 40,
      imageUrl: "img/sports-1.jpg",
      imageUrl2: "img/sports-2.jpg",
      imageUrl3: "img/sports-3.jpg",
      imageUrl4: "img/sports-4.jpg",
      imageUrl5: "img/sports-5.jpg",
      des: "100000",
      qty: 1,
      ca: "Arrivals",
      category : "Product"
    },
    {
      id: 18,
      title: "Hat",
      price: 40,
      imageUrl: "img/4.jpg",
      imageUrl2: "img/Hat-1.jpg",
      imageUrl3: "img/Hat-2.jpg",
      imageUrl4: "img/Hat-3.jpg",
      imageUrl5: "img/Hat-3.jpg",
      des: "100000",
      qty: 1,
      ca: "Arrivals",
      category : "Product"
    },
        {
      id: 14,
      title: "Shorts",
      price: 40,
      imageUrl: "img/shorts-2.jpg",
      imageUrl2: "img/shorts-1.jpg",
      imageUrl3: "img/shorts3.jpg",
      imageUrl4: "img/shorts4.jpg",
      imageUrl5: "img/shorts5.jpg",
      des: "100000",
      qty: 1,
      ca: "Arrivals",
      category : "Product"
    },
        {
      id: 15,
      title: "Shirt",
      price: 40,
      imageUrl: "img/shirt-2.jpg",
      imageUrl2: "img/2.jpg",
      imageUrl3: "img/3.jpg",
      imageUrl4: "img/shirt-1.jpg",
      imageUrl5: "img/clothes-1.jpg",
      des: "100000",
      qty: 1,
      ca: "Arrivals",
      category : "Product"
    },
        {
      id: 16,
      title: "Shorts",
      price: 40,
      imageUrl: "img/shorts-1.jpg",
      imageUrl2: "img/shorts-2",
      imageUrl3: "img/shorts3.jpg",
      imageUrl4: "img/shorts4.jpg",
      imageUrl5: "img/shorts5.jpg",
      des: "100000",
      qty: 1,
      ca: "Toprated",   
      category : "Product"
    },

  ];
